#include <iostream>
#include "main.h"
#include "models/Human.h"

using namespace std;
using namespace cv;

int detect_interval = 5;
int id = 0;
HOGDescriptor hog;
Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method

Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
VideoCapture *cap;
Mat prevMaskedGray, maskedGray, gray, img;
vector<Rect> foundLocations;
vector<double> foundWeights;
vector<Ptr<Human>> identified;
Mat drawingImage, clearMaskedImg;

double ticks = 0;
double dt = 0;

Rect trimRect(Rect r);

void getForegroundMask(const Mat &curImage, Mat &mask);

void draw_identified(Mat img, vector<Ptr<Human>> identified);

void draw_detections(Mat frame, vector<Rect> rects);

void init();

void drawing();

void updateIdentified(const Rect &rect, const Ptr<Human> &human, const Ptr<Human> &best);

void newIdentified(const Rect &rect, Ptr<Human> &human);

Ptr<Human> getBestMatch(Ptr<Human> human, Rect rect_);

void applyAlgorithm();

void draw_points(Mat img, vector<Ptr<Human>> identified);

void getDt();

void processKalmans(double dt);

void calcOpticalFlows();

void markAllAsLost();


cv::Scalar randColor() {
    return Scalar(rand() % 256, rand() % 256, rand() % 256);
}

int main() {
    init();


    int notFoundCount = 0;
    int frame_idx = 0;
    while (cap->isOpened()) {

        getDt();

        cap->read(img);
        if (img.empty()) {
            break;
        }

////        resize(img, img, Size(0, 0), 2, 2, INTER_LANCZOS4);
        cvtColor(img, gray, COLOR_BGR2GRAY);
        getForegroundMask(img, fgMaskMOG2);
        cvtColor(clearMaskedImg, maskedGray, COLOR_BGR2GRAY);
        clearMaskedImg.copyTo(drawingImage);

        if (prevMaskedGray.empty())
            maskedGray.copyTo(prevMaskedGray);

        calcOpticalFlows();
        processKalmans(dt);

        if (frame_idx % detect_interval == 0) {
            applyAlgorithm();
        }

        drawing();

        char key = (char) waitKey(30);
        switch (key) {
            case 'q':
            case 'Q':
            case 27: //escape key
                return 0;
            default:
                break;
        }

        frame_idx++;

        for (Ptr<Human> h : identified) {
            h->opticalFlow.swapPoints();
        }

        cv::swap(prevMaskedGray, maskedGray);

        if (frame_idx % detect_interval == 0) {
            markAllAsLost();
        }
    }

    delete cap;

    return 0;
}

void markAllAsLost() {
    for (Ptr<Human> h : identified) {
        h->lost = true;
    }
}

void calcOpticalFlows() {
    for (Ptr<Human> h : identified) {
        h->opticalFlow.calculate(prevMaskedGray, maskedGray, h->point);
    }
}

void processKalmans(double dt) {
    for (Ptr<Human> h : identified) {
        if (h->kalman.notFoundCount > 100) h->kalman.found = false;
        if (h->lost) h->kalman.notFoundCount++;
        h->kalman.predict(dt);
        h->kalman.drawPredicted(drawingImage);
    }
}

void getDt() {
    double precTick = ticks;
    ticks = (double) getTickCount();
    dt = (ticks - precTick) / getTickFrequency(); //seconds
}

void applyAlgorithm() {
    hog.detectMultiScale(gray, foundLocations, foundWeights, hogParams.hitThreshold, hogParams.winStride,
                         hogParams.padding,
                         hogParams.scale, hogParams.finalThreshold, hogParams.useMeanShift);
    for (Rect rect: foundLocations) {
        Ptr<Human> human = new Human();
        Ptr<Human> best = getBestMatch(human, rect);
        if (!best.empty()) {
            updateIdentified(rect, human, best);
            Rect trimmed = trimRect(rect);
            best->kalman.resetCounter();
            best->kalman.update(trimmed);
        } else {
            newIdentified(rect, human);
        }
    }
}

Ptr<Human> getBestMatch(Ptr<Human> human, Rect rect) {
    Ptr<Human> bestHuman;
    Rect trimmed = trimRect(rect);
    human->histDescriptor.extractFeatures(img, trimmed, fgMaskMOG2);
    double best_comparison = 0;
    for (vector<Ptr<Human>>::iterator it = identified.begin(); it != identified.end(); it++) {
        double comparison = human->histDescriptor.compare(((*it)->histDescriptor));
        if (comparison > COMPARISON_THRESHOLD && best_comparison < comparison) {
            best_comparison = comparison;
            bestHuman = *it;
        }
    }
    return bestHuman;
}

void newIdentified(const Rect &rect, Ptr<Human> &human) {
    human->id = id++;
    human->point = Point(rect.x + rect.width / 2, rect.y + rect.height / 2);
    human->color = randColor();
    Rect trimmed = trimRect(rect);
    human->opticalFlow.getOpticalFlowPoints(trimmed, maskedGray);
    identified.push_back(human);
}



void updateIdentified(const Rect &rect, const Ptr<Human> &human,
                      const Ptr<Human> &best) {
    //                    cout << "Best comparison for " << (*best)->id << " | " << best_comparison << endl;
    best->lost = false;

    best->point = Point(rect.x + rect.width / 2, rect.y + rect.height / 2);
    if (++best->histDescriptor.counter > HISTORY) {
        best->histDescriptor = human->histDescriptor;
        best->gaborDescriptor = human->gaborDescriptor;
        best->histDescriptor.counter = 0;
    }
}

void drawing() {
    draw_detections(drawingImage, foundLocations);
    draw_identified(drawingImage, identified);
    draw_points(drawingImage, identified);

    imshow(winname, drawingImage);
}

void draw_points(Mat img, vector<Ptr<Human>> identified) {
    for (Ptr<Human> h : identified) {
        h->opticalFlow.drawPoints(drawingImage, h->color);
    }
}

void init() {
    namedWindow(winname, WINDOW_KEEPRATIO);
    hog.setSVMDetector(HOGDescriptor::getDefaultPeopleDetector());
    pMOG2 = createBackgroundSubtractorMOG2(); //MOG2 approach
    cap = new VideoCapture(VIDEO_PATH);
}

void getForegroundMask(const Mat &curImage, Mat &mask) {
    int morph_elem = 2;
    pMOG2->apply(curImage, mask, 0);

    // Since MORPH_X : 2,3,4,5 and 6

    medianBlur(mask, mask, 2 * 2 + 1);

    int morph_size2 = 3;

    morphologyEx(mask, mask, 3,
                 getStructuringElement(morph_elem, Size(2 * morph_size2 + 1, 2 * morph_size2 + 1),
                                       Point(morph_size2, morph_size2)));

    clearMaskedImg.release();
    img.copyTo(clearMaskedImg, fgMaskMOG2);
}

Rect trimRect(Rect rect) {
    int pad_w = (int) (0.15 * rect.width);
    int pad_h = (int) (0.05 * rect.height);
    Point pt1(rect.x + pad_w, rect.y + pad_h);
    Point pt2(rect.x + rect.width - pad_w, rect.y + rect.height - pad_h);
    return Rect(pt1, pt2);
}

void draw_detections(Mat frame, vector<Rect> rects) {
    for (Rect rect : rects) {
        int pad_w = (int) (0.15 * rect.width);
        int pad_h = (int) (0.05 * rect.height);
        Point pt1(rect.x + pad_w, rect.y + pad_h);
        Point pt2(rect.x + rect.width - pad_w, rect.y + rect.height - pad_h);

        putText(frame, "Human", pt1, CV_FONT_HERSHEY_PLAIN, 1, Scalar(255, 255, 255), 1);
        rectangle(frame, pt1, pt2, Scalar(0, 255, 0));
        circle(frame, Point(rect.x + rect.width / 2, rect.y + rect.height / 2), 3, Scalar(0, 0, 255));
    }
}

void draw_identified(Mat img, vector<Ptr<Human>> identified) {
    for (Ptr<Human> human : identified) {
        if (!human->lost) {
            string str = "ID:";
            str.append(to_string(human->id));

            putText(img, str, human->point, CV_FONT_HERSHEY_PLAIN, 1, Scalar(255, 255, 255), 1);
            circle(img, human->point, 4, human->color);
        }
    }
}