#include <iostream>
#include "main.h"
#include "models/Human.h"

using namespace std;
using namespace cv;

int detect_interval = 5;
int id = 0;
HOGDescriptor hog;
Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method

Ptr<BackgroundSubtractorMOG2> pMOG2; //MOG2 Background subtractor
VideoCapture *cap;
Mat prevMaskedGray, maskedGray, gray, img;
vector<Rect> foundLocations;
vector<double> foundWeights;
vector<Ptr<Human>> identified;
Mat drawingImage, clearMaskedImg;

double ticks = 0;
double dt = 0;

Rect trimRect(Rect r);

void getForegroundMask(const Mat &curImage, Mat &mask);

void draw_identified(Mat img, vector<Ptr<Human>> identified);

void draw_detections(Mat frame, vector<Rect> rects);

void init();

void drawing();

void updateIdentified(const Rect &rect, const Ptr<Human> &human, const Ptr<Human> &best);

void newIdentified(const Rect &rect, Ptr<Human> &human);

Ptr<Human> getBestMatch(Ptr<Human> human, Rect rect_);

void applyAlgorithm(int frameId);

void draw_points(Mat img, vector<Ptr<Human>> identified);

void getDt();

void processKalmans(int i, int i1);

void calcOpticalFlows();

void markAllAsLost();

void draw_kalmans(Mat img, vector<Ptr<Human>> identified);

void swapPoints();

void processImage();

bool exit();

void calcCollisions(vector<Ptr<Human>> identified);

void calcBeforeAfter(vector<Ptr<Human>> identified);

cv::Scalar randColor() {
    return Scalar(rand() % 256, rand() % 256, rand() % 256);
}

int main() {
    init();
    int frame_idx = 0;
    while (cap->isOpened()) {
        cap->read(img);
        if (img.empty()) {
            break;
        }

        processImage();

        applyAlgorithm(frame_idx);

        frame_idx++;

        if (exit()) break;
    }

    delete cap;

    return 0;
}

bool exit() {
    char key = (char) waitKey(30);
    switch (key) {
        case 'q':
        case 'Q':
        case 27: //escape key
            return true;
        default:
            return false;
    }
}

void processImage() {
//    resize(img, img, Size(0, 0), 2, 2, INTER_LANCZOS4);
    cvtColor(img, gray, COLOR_BGR2GRAY);
    getForegroundMask(img, fgMaskMOG2);
    cvtColor(clearMaskedImg, maskedGray, COLOR_BGR2GRAY);
    clearMaskedImg.copyTo(drawingImage);

    if (prevMaskedGray.empty())
        maskedGray.copyTo(prevMaskedGray);
}

void swapPoints() {
    for (Ptr<Human> h : identified) {
        h->opticalFlow.swapPoints();
    }
}

void markAllAsLost() {
    for (Ptr<Human> h : identified) {
        h->lost = true;
    }
}

void calcOpticalFlows() {
    for (Ptr<Human> h : identified) {
        if (!h->collision && !h->reinit) {
            h->opticalFlow.calculate(prevMaskedGray, maskedGray, h->point, h->boudingBox.width, h->boudingBox.height);
        } else if (!h->collision && h->reinit) {
            h->opticalFlow.getOpticalFlowPoints(h->kalman.predRect, maskedGray);
            h->reinit = false;
        } else {
            h->opticalFlow.calculateWithCollision(h->move);
        }
        h->kalman.update(h->opticalFlow.boundingBox);
    }
}

void processKalmans(int width, int height) {
    getDt();
    for (Ptr<Human> h : identified) {
        if (h->kalman.notFoundCount > 100) {
            h->kalman.found = false;
//            h->opticalFlow.blocked = true;
            h->outOfWindow = true;
        }
        if (h->lost) h->kalman.notFoundCount++;
        h->kalman.predict(dt);
        if (h->kalman.center.y < 0 || h->kalman.center.y > height || h->kalman.center.x < 0 ||
            h->kalman.center.x > width) {
            h->outOfWindow = true;
        }
        h->predictHumanPosition();
    }
}

void getDt() {
    double precTick = ticks;
    ticks = (double) getTickCount();
    dt = (ticks - precTick) / getTickFrequency(); //seconds
}

void applyAlgorithm(int frameId) {
    cout << dt << endl;
    calcBeforeAfter(identified);
    calcCollisions(identified);
    calcOpticalFlows();
    processKalmans(img.cols, img.rows);

    if (frameId % detect_interval == 0) {
        hog.detectMultiScale(gray, foundLocations, foundWeights, hogParams.hitThreshold, hogParams.winStride,
                             hogParams.padding,
                             hogParams.scale, hogParams.finalThreshold, hogParams.useMeanShift);
        for (int i = 0; i < foundLocations.size(); i++) {
            Rect trimmed = trimRect(foundLocations[i]);

            Ptr<Human> human = new Human();
            Ptr<Human> best = getBestMatch(human, trimmed);
            if (!best.empty()) {
                updateIdentified(trimmed, human, best);
                best->kalman.resetCounter();
                best->kalman.update(trimmed);
            } else {
                newIdentified(trimmed, human);
            }
        }
    }

    drawing();

    swapPoints();

    cv::swap(prevMaskedGray, maskedGray);

    if (frameId % detect_interval == 0) {
        markAllAsLost();
    }
}

void calcBeforeAfter(vector<Ptr<Human>> identified) {
    for(Ptr<Human> h : identified) {
        h->calcBeforeAfter(h->kalman.center);
    }
}

Ptr<Human> getBestMatch(Ptr<Human> human, Rect rect) {
    Ptr<Human> bestHuman;
    human->histDescriptor.extractFeatures(img, rect, fgMaskMOG2);
    double best_comparison = 0;
    for (vector<Ptr<Human>>::iterator it = identified.begin(); it != identified.end(); it++) {
        double comparison = human->histDescriptor.compare(((*it)->histDescriptor));
        if (comparison > COMPARISON_THRESHOLD && best_comparison < comparison) {
            best_comparison = comparison;
            bestHuman = *it;
        }
    }
    return bestHuman;
}

void newIdentified(const Rect &rect, Ptr<Human> &human) {
    human->id = id++;
    human->point = Point(rect.x + rect.width / 2, rect.y + rect.height / 2);
    human->color = randColor();
    human->boudingBox = rect;
    human->opticalFlow.getOpticalFlowPoints(rect, maskedGray);
    identified.push_back(human);
}


void updateIdentified(const Rect &rect, const Ptr<Human> &human,
                      const Ptr<Human> &best) {
    //                    cout << "Best comparison for " << (*best)->id << " | " << best_comparison << endl;
    best->lost = false;
    best->opticalFlow.blocked = false;
    best->outOfWindow = false;
    best->boudingBox = rect;
    if (best->outOfWindow) {
        best->opticalFlow.points->clear();
        best->opticalFlow.getOpticalFlowPoints(rect, maskedGray);
    }
    best->point = Point(rect.x + rect.width / 2, rect.y + rect.height / 2);
    if (++best->histDescriptor.counter > HISTORY) {
        best->histDescriptor = human->histDescriptor;
        best->gaborDescriptor = human->gaborDescriptor;
        best->histDescriptor.counter = 0;
    }
}

void drawing() {
//    draw_detections(drawingImage, foundLocations);
//    draw_identified(drawingImage, identified);
    draw_kalmans(drawingImage, identified);
    draw_points(drawingImage, identified);


    imshow(winname, drawingImage);
}

void calcCollisions(vector<Ptr<Human>> identified) {
    for_each(identified.begin(), identified.end(), [](Ptr<Human> &human) { human->collision = false; });
    for (Ptr<Human> h1 : identified) {
        for (Ptr<Human> h2 : identified) {
            if (h1->id != h2->id && !h1->outOfWindow && !h2->outOfWindow) {
                Rect intersect = h1->boudingBox & h2->boudingBox;
                if (intersect.width > 0 && intersect.height > 0) {
                    h1->collision = true;
                    h2->collision = true;
                    h1->reinit = true;
                    h2->reinit = true;
                }
            }
        }
    }
}

void draw_kalmans(Mat img, vector<Ptr<Human>> identified) {
    for (Ptr<Human> h: identified) {
        if (h->kalman.found) {
            h->kalman.drawPredicted(img);
        }
    }
}

void draw_points(Mat img, vector<Ptr<Human>> identified) {
    for (Ptr<Human> h : identified) {
        h->opticalFlow.drawPoints(drawingImage, h->color);
    }
}

void init() {
    namedWindow(winname, WINDOW_KEEPRATIO);
    hog.setSVMDetector(HOGDescriptor::getDefaultPeopleDetector());
    pMOG2 = createBackgroundSubtractorMOG2(); //MOG2 approach
    cap = new VideoCapture(VIDEO_PATH);
}

void getForegroundMask(const Mat &curImage, Mat &mask) {
    int morph_elem = 2;
    pMOG2->apply(curImage, mask, 0);
    // Since MORPH_X : 2,3,4,5 and 6

    medianBlur(mask, mask, 2 * 2 + 1);

    int morph_size2 = 3;

    morphologyEx(mask, mask, 3,
                 getStructuringElement(morph_elem, Size(2 * morph_size2 + 1, 2 * morph_size2 + 1),
                                       Point(morph_size2, morph_size2)));

    clearMaskedImg.release();
    curImage.copyTo(clearMaskedImg, fgMaskMOG2);
}

Rect trimRect(Rect rect) {
    int pad_w = (int) (0.15 * rect.width);
    int pad_h = (int) (0.05 * rect.height);
    Point pt1(rect.x + pad_w, rect.y + pad_h);
    Point pt2(rect.x + rect.width - pad_w, rect.y + rect.height - pad_h);
    return Rect(pt1, pt2);
}

void draw_detections(Mat frame, vector<Rect> rects) {
    for (Rect rect : rects) {
        int pad_w = (int) (0.15 * rect.width);
        int pad_h = (int) (0.05 * rect.height);
        Point pt1(rect.x + pad_w, rect.y + pad_h);
        Point pt2(rect.x + rect.width - pad_w, rect.y + rect.height - pad_h);

        putText(frame, "Human", pt1, CV_FONT_HERSHEY_PLAIN, 1, Scalar(255, 255, 255), 1);
        rectangle(frame, pt1, pt2, Scalar(0, 255, 0));
        circle(frame, Point(rect.x + rect.width / 2, rect.y + rect.height / 2), 3, Scalar(0, 0, 255));
    }
}

void draw_identified(Mat img, vector<Ptr<Human>> identified) {
    for (Ptr<Human> human : identified) {
        if (human->kalman.found) {
            string str = "ID:";
            str.append(to_string(human->id));

            putText(img, str, human->predicted, CV_FONT_HERSHEY_PLAIN, 1, Scalar(255, 255, 255), 1);
            circle(img, human->predicted, 4, human->color);
        }
    }
}