//
// Created by hya on 05.07.16.
//

#ifndef REIDENTIFICATION_REIDENTIFICATIONDATA_H
#define REIDENTIFICATION_REIDENTIFICATIONDATA_H

#include "models/Human.h"
#include "haar/HaarDetector.h"
#include "HOGTrainer.h"

class ReidentificationData {
public:
    ReidentificationData() {};
    bool exiting;
    char *fileName;
    int detect_interval = 5;
    int id = 0;
    HOGDescriptor hog;
    HOGDescriptor angleHog;
    Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
    HaarDetector haarDetector;
    HOGTrainer *hogTrainer;

    Ptr<BackgroundSubtractorMOG2> pMOG2; //MOG2 Background subtractor
    VideoCapture *cap;
    Mat prevMaskedGray, maskedGray, gray, img;
    vector<Rect> foundLocations;
    vector<double> foundWeights;
    vector<Rect> foundAngleLocations;
    vector<double> foundAngleWeights;
    vector<Ptr<Human>> identified;
    Mat drawingImage, clearMaskedImg;

    double ticks = 0;
    double dt = 0;
};


#endif //REIDENTIFICATION_REIDENTIFICATIONDATA_H
